# Default values for audit-pipeline.

rbac:
  create: true
  clusterRole:
    name: cr-audit-pipeline
    rules:
      - apiGroups:
          - autoscaling.k8s.io
        resources:
          - verticalpodautoscalers
        verbs:
          - get
          - list

  clusterRoleBinding:
    name: crb-audit-pipeline

  serviceAccount:
    create: true
    automount: true
    # The name of the service account to use.
    name: "sa-audit-pipeline"

configMap:
  name: "cm-audit-pipeline"

cronJob:
  create: true
  name: cj-audit-pipeline
  schedule: "* */12 * * *"
  successfulJobsHistoryLimit:
  failedJobsHistoryLimit:
  jobTemplate:
    # Specifies the number of retries before marking this job failed. Defaults to 6
    backoffLimit:
    # Specifies the desired number of successfully finished pods the job should be run with.
    completions:
    name: po-audit-pipeline
    image:
      repository: paulofabianoo/audit-pipeline
      # This sets the pull policy for images.
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v0.1.0"
    restartPolicy: OnFailure
    command:
    - sh
    - -c 
    - cd /audit-pipeline ; cat command | sh
    # args:
    # URL for send the json file with the recommendations.
    # I'm using webhook.site for this at this moment
    sendResultsUrl: https://webhook.site/cdcd1b17-7ed2-4f6b-af4a-e734c6fa465a

podSecurityContext:
  fsGroup: null

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: null

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
