apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  command: |-

    kubectl get vpa -A

    for vpa in $(kubectl get vpa -A --no-headers | wc -l) ; \
        do kubectl get vpa -A --no-headers | awk '{print $2,$1}' | xargs -n2 sh -c 'kubectl get vpa $0 -n $1 -o json' | jq -s '.' >> /tmp/recommendations.json  ; \
        done

    curl --upload-file /tmp/recommendations.json $URL_PIPELINE