{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "audit-pipeline.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}