apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  command: |
    for vpa in $(kubectl get vpa -A --no-headers | wc -l) ; \
    do kubectl get vpa -A --no-headers | awk '{print $2,$1}' | xargs -n2 sh -c 'kubectl get vpa $0 -n $1 -o json' | jq -s '.' >> recommendations.json  ; \
    done