apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-audit-pipeline
rules:
- apiGroups:
  - "autoscaling.k8s.io/v1"
  resources:
  - verticalpodautoscalers
  verbs:
  - get
  - list